 ### Topic Covered: Numpy

In [1]:
#Install numpy and scipy if you don't have it already installed.
#importing necessary packages
import numpy as np
from numpy import linalg as LA
from scipy import stats

### Practical Questions
1. Write a python code for addition, subtraction and multiplication of two 4x4 matrices

In [2]:
#defining matrix
m = np.matrix([[1,2,3,4], [5,6,7,8],[9,10,11,12],[13,14,15,16]])
n = np.matrix([[2,4,6,8], [1,3,5,9],[7,6,5,4],[2,3,4,5]])

#operations
print("Multiplication\n",m*n)
print("Addition\n",m+n)
print("Subtraction\n",m-n)


Multiplication
 [[ 33  40  47  58]
 [ 81 104 127 162]
 [129 168 207 266]
 [177 232 287 370]]
Addition
 [[ 3  6  9 12]
 [ 6  9 12 17]
 [16 16 16 16]
 [15 17 19 21]]
Subtraction
 [[-1 -2 -3 -4]
 [ 4  3  2 -1]
 [ 2  4  6  8]
 [11 11 11 11]]


2. Create a 5 by 2 integer array from a range between 150 to 250 such that the difference between each element is 10. Print the same.

In [3]:
#generating array using reshape
arr = np.arange(150, 250, 10)
arr = arr.reshape(5,2)
print (arr)

[[150 160]
 [170 180]
 [190 200]
 [210 220]
 [230 240]]


3. Consider two matrices
M1=([[2,3,4], [6,5,2], [6,7,3]])
M2=([[1,4,2], [4,3,6],[5,9,8]]) Calculate manually as well as develop the python program for the following:
(1) matrix multiplication (dot product) (2) inner product (3) cross product (4) outer product

In [4]:
m = np.matrix([[2,3,4], [6,5,2], [6,7,3]])
n = np.matrix([[1,4,2], [4,3,6],[5,9,8]])
print(m,"\n\n",n)

[[2 3 4]
 [6 5 2]
 [6 7 3]] 

 [[1 4 2]
 [4 3 6]
 [5 9 8]]


In [5]:
#multiplication(dot product)
result = np.dot(m, n)
print(result)

[[34 53 54]
 [36 57 58]
 [49 72 78]]


In [6]:
#multiplication(Inner product)
np.inner(m,n)


matrix([[ 22,  41,  69],
        [ 30,  51,  91],
        [ 40,  63, 117]])

In [7]:
#multiplication(cross product)
np.cross(m,n)

array([[-10,   0,   5],
       [ 24, -28,  -2],
       [ 29, -33,  19]])

In [8]:
np.outer(m,n)

array([[ 2,  8,  4,  8,  6, 12, 10, 18, 16],
       [ 3, 12,  6, 12,  9, 18, 15, 27, 24],
       [ 4, 16,  8, 16, 12, 24, 20, 36, 32],
       [ 6, 24, 12, 24, 18, 36, 30, 54, 48],
       [ 5, 20, 10, 20, 15, 30, 25, 45, 40],
       [ 2,  8,  4,  8,  6, 12, 10, 18, 16],
       [ 6, 24, 12, 24, 18, 36, 30, 54, 48],
       [ 7, 28, 14, 28, 21, 42, 35, 63, 56],
       [ 3, 12,  6, 12,  9, 18, 15, 27, 24]])

4. Randomly generate the marks of the 85 students in the range of 42 to 93. Write a NumPy 
program to compute the 84 percentile for all elements in a given array. (Hint: use
np.random. randint(start,stop,no_of_items) for list
generation) (Hint: Use np.percentile

In [9]:
#84 percentile for all elements

arr=np.random.randint(42,93,85)
print(arr,'\n')

per=np.percentile(arr,84)
print("84th percentile:",per)




[86 86 87 62 57 64 61 46 92 56 80 92 75 56 43 85 58 69 63 49 72 85 56 68
 42 88 46 42 78 51 88 73 75 82 74 50 85 60 63 64 86 66 43 55 56 81 64 92
 49 89 69 47 91 85 71 78 87 70 71 89 48 81 87 50 86 81 59 63 64 65 55 49
 81 84 50 85 53 87 81 68 84 57 89 60 55] 

84th percentile: 86.0


5. Write a NumPy program to compute the eigenvalues and right eigenvectors of a given square 
array.
Arr =([[1,4,8], [8,9,2],[9,7,8]])
HINT: Use linear algebra package under numpy. Add these statements i.e. for eigenvalues,
import numpy as np
from numpy import linalg
np.linalg.eig(a)


In [10]:
#eigenvalues and right eigenvectors
Arr =([[1,4,8], [8,9,2],[9,7,8]])
w, v =np.linalg.eig(Arr)
print( "Eigenvalues\n",w)
print( "Eigenvectors\n",v)


Eigenvalues
 [18.61713304 -4.50451282  3.88737977]
Eigenvectors
 [[-0.44798294 -0.82768979  0.36471887]
 [-0.52339057  0.43844259 -0.77347804]
 [-0.7248266   0.35028233  0.51837426]]


## Additional questions:
1. Compute the determinant and inverse of a given square array manually as well as
programmatically using python. Arr = [[1,4,8], [8,9,2],[9,7,8]]


In [11]:
#determinant
a = [[1,4,8], [8,9,2],[9,7,8]]
print("Determinant:")
print(np.linalg.det(a))

Determinant:
-326.0


In [12]:
#inverse
print("Inverse:")
print(np.linalg.inv(a))


Inverse:
[[-0.17791411 -0.07361963  0.19631902]
 [ 0.14110429  0.19631902 -0.19018405]
 [ 0.07668712 -0.08895706  0.07055215]]


2. Write a NumPy program to compute the following for the given array. Mean, median, mode,
variance, and standard deviation. 

In [13]:
#mean
print(np.mean(a))

6.222222222222222


In [14]:
#median
print(np.median(a))

8.0


In [15]:
#mode
a= np.array([[1,4,8], [8,9,2],[9,7,8]])
print(stats.mode(a,axis=None))

ModeResult(mode=array([8]), count=array([3]))


In [16]:
#Standard deviation
print(np.std(a))

2.8974232912011773


In [17]:
#variance
print(np.var(a))

8.395061728395062


3. Write a NumPy program to compute the covariance matrix of two given arrays

In [18]:
#covariance
a1= np.array([[1,4,8], [8,9,2],[9,7,8]])
a2= np.array([[1,2,6], [2,5,7],[3,6,9]])
print("Covariance: \n",np.cov(a1,a2))

Covariance: 
 [[ 12.33333333 -11.16666667  -1.5          9.           8.66666667
   10.5       ]
 [-11.16666667  14.33333333  -0.5         -9.5         -6.83333333
   -9.        ]
 [ -1.5         -0.5          1.          -0.5         -1.5
   -1.5       ]
 [  9.          -9.5         -0.5          7.           6.
    7.5       ]
 [  8.66666667  -6.83333333  -1.5          6.           6.33333333
    7.5       ]
 [ 10.5         -9.          -1.5          7.5          7.5
    9.        ]]


4. Write a Python program to count number of occurrences of each value in a given array of
non-negative integers. USE bincount

In [19]:
a = [0, 1, 6, 1, 4, 1, 2, 2, 7,112]
print(np.bincount(a))

[1 3 2 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 1]


5. Write a NumPy program to compute the sum of the diagonal element of a given array. USE
trace.

In [20]:
#trace
a = [[1,4,8], [8,9,2],[9,7,8]]
print(np.trace(a))

18


6. You are given a space separated list of nine integers. Your task is to convert this list into
a 3x3 NumPy array.
Eg: input: 1 2 3 4 5 6 7 8 9
Output:
[ [1 2 3]
[4 5 6]
[7 8 9] ]

In [21]:
def listtomat(r,c):
 t=list(map(int,input().split(' ')))
 s=list()
 for i in range(r):
  s.append(t[:c])
  t=t[c:]
 return np.array(s)

mat=listtomat(3,3)
print(mat)

[list([5]) list([]) list([])]


C:\Users\HP\AppData\Local\Temp\ipykernel_16856\200069143.py:7: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return np.array(s)


Additional Codes

In [22]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [23]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [24]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)

[[[[[1 2 3 4]]]]]
